version: '2'

services:
    web:
        container_name: php-apache
        build: './build/php'
        volumes:
            - ./app:/var/www/html/
        ports:
            - 8084:80
        depends_on:
            - db
    db:
        volumes:
            - ./src/database:/var/lib/mysql
        ports:
            - "3308:3306"
        build: './build/mysql'
        environment:
            - MYSQL_ROOT_PASSWORD=root
    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: MyPhpAdmin
        ports:
            - "8086:80"
        depends_on:
            - db
volumes:
    app:
    database:
